services:
  - type: web
    name: real-estate-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    redirects:
      - source: /*
        destination: /index.html
        statusCode: 200
