services:
  - type: web
    name: real-estate-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    redirects:
      - source: /*
        destination: /index.html
        type: permanent
      - source: /home/*
        destination: /index.html
        type: permanent
      - source: /project/*
        destination: /index.html
        type: permanent
